# Dependencies
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll/scholar

# Permalinks
# permalink:           pretty

# Setup
title:               'Shale Xiong'
url:                 'https://www.shalexiong.com'
baseurl:             ''

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:         >
    Shale Xiong's personal page.

# The tags listed as entries in the sidebar
# sidebar_tags:        []

# Fallback image and color if not overwritten for tag or post
image:               '/img/bk.jpg'
icon:                '/img/favicon.ico'
color:               '#A85641'

# Fonts
font:                '"PT Serif", Georgia, serif'
font_accent:         '"Roboto Slab", "PT Serif", Georgia, serif'
load_google_fonts:   'Roboto+Slab:700|PT+Serif:400,400italic,700,700italic'

# About yourself
author:
  name:               'Shale Xiong'

  # This photo will be used in the about section
  photo:              '/img/shale-xiong.jpg'

  # Social media icons in sidebar
  # Comment/uncommet to show/hide
  # Icons appear in order, can be rearranged:
  social:
    # facebook:        _username_
    # twitter:         _username_
    # google:          _number_
    # vk:              _username_
    # youtube:         _string___string___string_
    # vimeo:           _username_
    # vine:            _username_
    # spotify:         user/_number_
    # soundcloud:      _username_
    # lastfm:          _username_
    # instagram:       _username_
    # flickr:          _string_@_string_
    # 500px:           _username_
    # dribbble:        _username_
    # behance:         _username_
    # deviantart:      _username_
    # ello:            _username_
    # twitch:          _username_
    # steam:           _number_
    # reddit:          _username_
    # tumblr:          _username_
    # pinterest:       _username_
    # foursquare:      _number_
    # yelp:            _string_
    github:            ShaleXIONG
    # stackoverflow:   _number_/_username_
    # npm:             _username_
    # hackernews:      _username_
    # trello:          _firstname__lastname_
    linkedin:          shale-xiong-5653379a
    # xing:            _firstname___lastname__counter_
    # blogger:         _number_
    # delicious:       _username_
    # stumbleupon:     _username_
    # paypal:          _username_

# Remove to disable Google Anaylics
google_analytics_id: 'UA-84025722-2'

# Setting a disqus subdomain will enable the comment section
# disqus:            <username>

kramdown:
  math_engine:       mathjax
  math_engine_opts:
    preview:         true
    preview_as_code: true

scholar:
  source: publications
  bibliography: ref.bib
  bibliography_template: publication-entry
  details_link: ''
  details_dir: publications
  details_layout: publication.html

  use_raw_bibtex_entry: true
  bibtex_skip_fields: ['note']
  bibtex_filters:
    - superscript
    - latex

  sort_by: year, month
  order: descending
  group_order: descending
  bibliography_group_tag: 'h3,h4,h5,h6'

  repository: publications

compress_html:
  comments:          ["<!-- ", " -->"]
  clippings:         all
  endings:           all
  ignore:
    envs:            [local]

sass:
  style:             compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - "*.tex"
  - "*.aux"
  - "*.dvi"
  - "*.out"
  - "*.log"
  - bitbucket-pipelines.yml
  - Rakefile
  - google.json
